### ISSUE TITLE
Play/pause issues on Big Sur

### ISSUE THREAD

**Issue by 63ba1f46da** [michaelvillar/timer-app#95]
Play/pause button becomes unclickable like it doesn't exist. The same happens to the blue dragging thingy that sets the time. Once the timer is set and running. It cannot be changed nor paused. 

Further there is now a white border at the bottom. (See screenshot) 

(On Big Sur beta running on Macbook Air 2017)
1. Open the timer
2. Set the timer
3. Let it run for 5 sec then try to pause. Nothing happens
4. Try to drag the blue thingy around. Nothing happens 

![Screenshot 2020-08-14 at 8 03 03 AM](https://user-images.githubusercontent.com/15912881/90207747-b2d8a780-de04-11ea-90e4-dd0b7ba607aa.png)

**Desktop**
 - OS version: macOS 11 beta]
 - Version: 1.5.5

**Comment by karbassi** [comment]
Thanks @espresso-math for reporting this. We'll need people to test the new OS for us.

No good that the app breaks within it.

**Comment by 63ba1f46da** [comment]
Always happy to do what I can to help. Cannot stress how useful this app has become to me. I use it everyday.

**Comment by karbassi** [comment]
@espresso-math I'm glad. I'll install Big Sur soon to see what the issue is.

@robinstewart do you happen to have Big Sur installed?

**Comment by 63ba1f46da** [comment]
@robinstewart Yes, I updated to it a few days ago.

**Comment by 63ba1f46da** [comment]
@robinstewart  I have a new observation. The play/pause works as long as I don't try to move the blue slider. As soon as I try to move the blue slider the whole timer window moves with he cursor. After that the play/pause doesn't work and I have to restart the timer or create a new one. Once it gets stuck, if I make a new timer I drag it and set the timer but the same problem appears if I try to drag the slider around change the time.

**Comment by robinstewart** [comment]
Thanks @espresso-math. Unfortunately no I don't have Big Sur installed yet. I guess it's not too surprising something broke, given the significant visual changes in Big Sur.

If anyone else wants to look into this, Xcode > Debug menu > View Debugging > Capture View Hierarchy has been helpful to me in the past...

**Comment by Bendetta** [comment]
When running this locally on Big Sur, the mouseDown event is never being hit so `didDrag` has no way of being reset to false. The other events seemed to be firing reliably.

**Comment by silomia** [comment]
It is working for me now, as expected, with the new Timer 1.6 on Big Sur 11.1.

**Comment by phortuin** [comment]
Hate to bring this issue up again, but @peasarechic’s issue is still very much alive

> As soon as I try to move the blue slider the whole timer window moves with he cursor. 

![timer](https://user-images.githubusercontent.com/137299/106164280-13c52380-618a-11eb-85f2-8e60fc4e7662.gif)

This is on MacOS 11.1 (on a Macbook Air M1, to be exact).

**Comment by karbassi** [comment]
@phortuin can you share what version of the app you're using?

**Comment by phortuin** [comment]
@karbassi 1.6.0, installed via Homebrew

**Comment by karbassi** [comment]
> @karbassi 1.6.0, installed via Homebrew

To pin-point the issue, could you uninstall and reinstall

```sh
brew uninstall --zap michaelvillar-timer
brew install --cask michaelvillar-timer
```

**Comment by phortuin** [comment]
Done, behaviour hasn't changed:

```bash
$ brew uninstall --zap michaelvillar-timer
==> Implied `brew uninstall --cask michaelvillar-timer`
==> Backing App 'Timer.app' up to '/usr/local/Caskroom/michaelvillar-timer/1.6.0
==> Removing App '/Applications/Timer.app'
Warning: No zap stanza present for Cask 'michaelvillar-timer'
==> Removing all staged versions of Cask 'michaelvillar-timer'

$ brew install --cask michaelvillar-timer 
==> Downloading https://github.com/michaelvillar/timer-app/releases/download/1.6
==> Downloading from https://github-releases.githubusercontent.com/55126195/1078
######################################################################## 100.0%
==> Installing Cask michaelvillar-timer
==> Moving App 'Timer.app' to '/Applications/Timer.app'
🍺  michaelvillar-timer was successfully installed!
```

Specs have changed a bit since last time: MacOS 11.2 on a MacBook Air M1, using an external 4k screen at 1920×1080 (2× pixel ratio)

@karbassi I found something that is probably helpful: the intended behaviour works up to 4 minutes. If I drag up to 3:50, I can change the timer. If I drag over 4:00, I will drag the whole window.

Edit: I’m trying to pinpoint, I can change it from up to 4:20 or so if I click the exactly right pixel. So it seems that there is an invisible boundary, within which I can drag the timer, and this area extends to somewhere near where the arrow is at 4:20. And it works at the other end of the timer as well: I can drag the timer while it’s near 53 minutes or higher.

![image](https://user-images.githubusercontent.com/137299/106887184-16250180-66e5-11eb-97a3-987a4da14818.png)

**Comment by karbassi** [comment]
Update: I've taken about 2 hours to look into this but with no luck. It is broken in Big Sur (11.2.1) from my testing and probably broken in 11.2.x.

@robinstewart do you have time to take a look?

**Comment by mbeynon** [comment]
This is still broken in 14.1.2.  It forces me to create a new timer every time I need to change an existing timer with the blue handle in the lower part of the window, and pause just cannot be used.
